version: "3.8"

services:
  node2:
    image: jykaswift/blockchain
    container_name: node2
    network_mode: host
    command: "2"
    stdin_open: true
    tty: true

  node1:
    image: jykaswift/blockchain
    container_name: node1
    network_mode: host
    command: "1"
    stdin_open: true
    tty: true

  node0:
    image: jykaswift/blockchain
    container_name: node0
    network_mode: host
    command: "0"
    stdin_open: true
    tty: true
    depends_on:
      - node2
      - node1


